# Generated by Django 6.1 on 2026-08-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('seguro_receber_mensagens', models.BooleanField(default=True, verbose_name='Seguro enviar msg?')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('melhor_horario', models.CharField(blank=True, max_length=50)),
                ('endereco', models.TextField(blank=True)),
                ('risco_imediato', models.CharField(blank=True, max_length=20)),
                ('medida_protetiva', models.CharField(blank=True, max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_tecnico', models.CharField(max_length=100)),
                ('data_atendimento', models.DateTimeField()),
                ('relato', models.TextField(verbose_name='Relato e Evolução')),
                ('proximo_passo', models.CharField(blank=True, max_length=200)),
                ('assistida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.assistida')),
            ],
        ),
    ]
