# Generated by Django 6.1 on 2026-08-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistida',
            name='apoio_psicologico',
            field=models.BooleanField(default=False, verbose_name='Apoio Psicológico'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='assistencia_social',
            field=models.BooleanField(default=False, verbose_name='Assistência Social'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='local_seguro',
            field=models.BooleanField(default=False, verbose_name='Possui local reservado e seguro para as videochamadas?'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='orientacao_juridica',
            field=models.BooleanField(default=False, verbose_name='Orientação Jurídica'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='qual_agressor_outro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Outro agressor (especificar)'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='tipo_agressor',
            field=models.CharField(blank=True, choices=[('conjugue', 'Cônjuge/Companheiro(a)'), ('ex_parceiro', 'Ex-parceiro(a)'), ('familiar', 'Familiar'), ('outro', 'Outro')], max_length=50, verbose_name='Quem é o agressor?'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='violencia_fisica',
            field=models.BooleanField(default=False, verbose_name='Física'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='violencia_moral',
            field=models.BooleanField(default=False, verbose_name='Moral'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='violencia_patrimonial',
            field=models.BooleanField(default=False, verbose_name='Patrimonial'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='violencia_psicologica',
            field=models.BooleanField(default=False, verbose_name='Psicológica'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='violencia_sexual',
            field=models.BooleanField(default=False, verbose_name='Sexual'),
        ),
        migrations.AddField(
            model_name='assistida',
            name='violencia_virtual',
            field=models.BooleanField(default=False, verbose_name='Virtual / Stalking'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='enc_abrigo',
            field=models.BooleanField(default=False, verbose_name='Casa de Abrigo / Acolhimento'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='enc_caps',
            field=models.BooleanField(default=False, verbose_name='Caps / Saúde Mental'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='enc_cras',
            field=models.BooleanField(default=False, verbose_name='Cras / Creas / Assist. Social'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='enc_deam',
            field=models.BooleanField(default=False, verbose_name='DEAM / Delegacia da Mulher'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='enc_defensoria',
            field=models.BooleanField(default=False, verbose_name='Defensoria Pública / Jurídico'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='enc_saude',
            field=models.BooleanField(default=False, verbose_name='Unidade de Saúde / Hospital'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='formato_predominante',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial'), ('hidrido', 'Híbrido')], default='online', max_length=20, verbose_name='Formato Predominante'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='observacoes_encaminhamento',
            field=models.TextField(blank=True, verbose_name='Outros / Observações do encaminhamento'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='status_atual',
            field=models.CharField(choices=[('ativo', 'Em atendimento ativo'), ('suspenso', 'Caso suspenso temporariamente'), ('alta', 'Processo de desligamento / Alta')], default='ativo', max_length=20, verbose_name='Status Atual do Acompanhamento'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro Inicial'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço Residencial (Opcional)'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='medida_protetiva',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('desejo', 'Desejo solicitar')], max_length=20, verbose_name='Possui Medida Protetiva de Urgência ativa?'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='melhor_horario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Melhor horário para contato'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='nome_completo',
            field=models.CharField(max_length=200, verbose_name='Nome Completo / Nome Social'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='risco_imediato',
            field=models.CharField(blank=True, choices=[('alto', 'Sim, risco alto'), ('moderado', 'Sim, risco moderado'), ('nao', 'Não no momento')], max_length=20, verbose_name='Existe risco imediato à integridade física ou à vida?'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='seguro_receber_mensagens',
            field=models.BooleanField(default=True, verbose_name='É seguro receber mensagens?'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='assistida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.assistida', verbose_name='Assistida'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='data_atendimento',
            field=models.DateTimeField(verbose_name='Data e Hora do Atendimento'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='proximo_passo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Próximo Passo / Agendamento'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='relato',
            field=models.TextField(verbose_name='Evolução do Caso, Relato e Intervenções Realizadas'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='responsavel_tecnico',
            field=models.CharField(max_length=100, verbose_name='Responsável Técnico Atual'),
        ),
    ]
