# Generated by Django 6.1 on 2026-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_assistida_apoio_psicologico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistida',
            name='local_seguro',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Possui local reservado e seguro para as videochamadas?'),
        ),
        migrations.AlterField(
            model_name='assistida',
            name='seguro_receber_mensagens',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='É seguro receber mensagens?'),
        ),
    ]
